### ISSUE TITLE
500 error when entering complex markdown into note body

### ISSUE THREAD

**Issue by fucx** [keybits/permanote#1]
I pasted the Markdown syntax example document from http://www.markitdown.net/markdown into a note, which causes a 500 error when saving and attempting to view the note.

I'm running it on my own Sandstorm server running Sandstorm 0.146.

This is the grain's log:

```
** SANDSTORM SUPERVISOR: Starting up grain.
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Feb/2016 12:44:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:35] "GET /static/css/note.min.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:35] "GET /static/css/hilite.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:36] "GET /static/js/jquery-1.12.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:36] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:36] "GET /static/js/jquery.inline-attachment.min.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:36] "GET /static/js/jquery.hotkeys.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2016 12:44:38] "GET /wed-24-feb-2016-at-12-38-38/ HTTP/1.1" 500 -
```

**Comment by keybits** [comment]
Thanks for the bug report Thomas. I think I know what causes this. I'll try and get it fixed in the next couple of days.

**Comment by fucx** [comment]
Thanks Tom, greatly appreciated. Please let me know if you need any additional information.

**Comment by keybits** [comment]
@fucx This should be fixed with version 0.1.2 which I just pushed to the app market. (It's not there yet - I think they have to manually approve updates.)

If you want to try with an updated spk you can get it here: https://oasis.sandstorm.io/shared/mhCdl7_rBr706QrGzzW5APXr5_uT7PY93oImbImIuzr

**Comment by fucx** [comment]
Thanks Tom, unfortunately though, this version of Permanote doesn't seem to work at all on my Sandstorm installation. I upgraded the app as well as the grain, but it doesn't finish loading, all I'm getting is a white screen and the browser's loading indicator spinning indefinitely.

**Comment by keybits** [comment]
Sorry about that! Just tested on Oasis and I can see the error. Strangely it works fine in my local Sandstorm environment.

I'll post a question on the Sandstorm dev forum. (This is an interesting learning process....)

**Comment by fucx** [comment]
not a problem at all, I'm not in a hurry.

feel free to let me know if I can be of assistance.

**Comment by keybits** [comment]
Aha - discovered what it is based on this commit to the Radicale package:

https://github.com/synchrone/sandstorm-radicale/commit/9ae8aeac03ac0c13f73150cbf831bac82311a0b5

Unfortunately that makes the spk go from 8mb to 53mb! So I think I'll revert to Python 2.

**Comment by keybits** [comment]
OK - I think that should do it. New spk at the link above. And republished to the app market.

**Comment by keybits** [comment]
And thanks for trying out the app - I have loads of plans to make it better. Let me know any feature suggestions :-)

**Comment by fucx** [comment]
Now it's working, thank you!
